config/routes.rb
Rails.application.routes.draw do
    root to: 'properties#index'

    match 'auth/sign_in', via: [:get, :post]
    get 'auth/sign_out'
    
    resources :properties do
        get :sale_offers, on: :collection
        get :renting_offers, on: :collection
        get :my_properties, on: :collection
    end
  resources :users
  resources :images

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    validates :login, presence: true, uniqueness: true
    validates :name, presence: true

    has_one :address, as: :addressable
    has_many :properties

    has_secure_password

    def add_property(property)
        self.properties << property
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:new,:create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :password, :password_confirmation,:name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>

  <div class="field">
    <%= form.text_field :name, placeholder: 'Your name', autocomplete: 'no' %>
    <p class="error_msg"> <%= user.errors.messages[:name].first %> </p>
  </div>

  <div class="field">
    <%= form.text_field :login, placeholder: 'Enter your email', type: 'email', autocomplete: 'no' %>
    <p class="error_msg"> <%= user.errors.messages[:login].first %> </p>
  </div>

  <div class="field">
    <%= form.password_field :password, placeholder: 'Choose a password' %>
    <p class="error_msg"> <%= user.errors.messages[:password].first %> </p>

  </div>

  <div class="field">
    <%= form.password_field :password_confirmation, placeholder: 'Confirm your password' %>
    <p class="error_msg"> <%= user.errors.messages[:password_confirmation].first %> </p>
  </div>

  <div class="actions">
  <% if user.new_record? %>
    <%= form.submit 'Submit' %>
  <% else %>
  <% end %>

  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="user">
<h1> New Account </h1>
<%= render 'form', user: @user %>
<%= link_to 'Sign in', auth_sign_in_url  %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>