config/routes.rb
Rails.application.routes.draw do
    root to: 'properties#index'

    match 'auth/sign_in', via: [:get, :post]
    get 'auth/sign_out'
    
    resources :properties do
        get :sale_offers, on: :collection
        get :renting_offers, on: :collection
        get :my_properties, on: :collection
    end
  resources :users
  resources :images

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/property.rb
class Property < ApplicationRecord
    # Validation 

    validates :description, presence: true
    validates :title, presence: true
    validates :landlord, presence: true
    validates :length, numericality: {greater_than: 0}
    validates :width, numericality: {greater_than: 0}
    validates :price, numericality: {greater_than: 0}
    belongs_to :landlord, class_name: 'User', foreign_key: 'user_id'
    has_many :images
    has_one :address, as: :addressable
    accepts_nested_attributes_for :address

    enum property_type: {
        "House" => 0,
        "Apartment" => 1,
        "Land" => 2,
        "Farm" => 3
    }
    enum offer_type: {
        "Sell" => 0,
        "Rent" => 1
    }    
    validates :property_type, inclusion: property_types.keys
    validates :offer_type, inclusion: offer_types.keys

    # Scopes

    scope :get_all, -> (city,country) do
        filter = build_filter(nil, city, country)
        includes(:address).where(filter).order('properties.created_at desc').limit(20)
    end

    scope :sale_offers, ->  (city,country) do
        filter = build_filter(:Sell, city, country)
        includes(:address).where(filter).order('properties.created_at desc').limit(20)
    end

    scope :renting_offers, -> (city,country) do
        filter = build_filter(:Rent, city, country)
        includes(:address).where(filter).order('properties.created_at desc').limit(20)        
    end

    def add_images(image)
        self.images << image
    end

    def total_area
        return self.length*self.width
    end

    private

    def self.build_filter(offer_type,city,country)
        filter = {}
        if offer_type 
            filter['offer_type'] = offer_type
        end
        if city
            filter['addresses.city'] = city
        end
        if country
            filter['addresses.country'] = country
        end
        return filter
    end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:index, :sale_offers, :renting_offers, :show]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.get_all(params["city"], params["country"])
  end

  def my_properties
    @properties = authenticated_user.properties
  end

  def sale_offers
    @properties = Property.sale_offers(params["city"], params["country"])
    render(action: :index)
  end

  def renting_offers
    @properties = Property.renting_offers(params["city"], params["country"])
    render(action: :index)
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
    @property.address = Address.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)
    @property.landlord = authenticated_user

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    puts 'kkkkkkkkkkkkkkkkkkkkk'
    puts property_params

    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to my_properties_properties_url , notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_property
    @property = Property.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def property_params
    params.require(:property).permit(:description, :total_area, :price, :title, :property_type, 
            :offer_type, :width, :length, address_attributes: [:city, :country, :description, :id])
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, cols: 20, rows: 10 %>
  </div>

  <div class="row">
    <div class="field">
    <%= form.label :property_type %>
    <%= form.select :property_type, Property.property_types.keys %>
  </div>

   <div class="field">
    <%= form.label :offer_type %>
    <% Property.offer_types.each do |offer_type, value| %>
       <%= form.radio_button :offer_type, offer_type %>  <%= offer_type %>
    <% end %>
  </div>

    <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, min: 0 %>
  </div>
  </div>



  <div class="field">
    <%= form.label :width %>
    <%= form.number_field :width, min: 0 %>
  </div>

  <div class="field">
    <%= form.label :length %>
    <%= form.number_field :length, min: 0 %>
  </div>  

   <%= form.fields_for :address do |address_form| %>
        <%= address_form.label :description, 'Address' %>
        <%= address_form.text_field :description %>

        <%= address_form.label :city %>
        <%= address_form.text_field :city %>
        <%= address_form.label :country %>
        <%= address_form.text_field :country %>

        <%= address_form.hidden_field :id %>

    <% end %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<div class="new">

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>
</div>

app/views/properties/index.html.erb
<div class="home container">
    <% @properties.each do |property| %>
        <div class="property">
            <img width="200" height="250" src="<%= "https://picsum.photos/seed/#{property.id}/200/250" %>"> 
             <p>
                <strong> <%= property.title + ' | ' + property.offer_type %> </strong>
            </p>
            <p>
            <%= number_to_currency(property.price) %>
            </p>
            <p> <%= property.width %> x <%= property.length %></p>
            <p> <%= link_to property.address.city,  city: property.address.city  %>, 
            <%=  link_to property.address.country,  country: property.address.country %></p>
        </div>
    <% end %>
</div>

app/views/properties/my_properties.html.erb
<div class="properties">
    <% if notice %>
        <p> <%= notice %> </p>
    <% end %>
    <table class="table-properties">
        <thead>
            <tr>
                <th># Id</th>
                <th># Title</th>
                <th># Type</th>
                <th># Offer Type </th>
                <th># Price</th>
                <th># Width</th>
                <th># Length</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @properties.each do |p| %>
                <tr>
                    <td><%= p.id %></td>
                    <td><%= p.title %></td>
                    <td><%= p.property_type %></td>
                    <td><%= p.offer_type %></td>
                    <td><%= number_to_currency p.price %></td>
                    <td><%= p.width %></td>
                    <td><%= p.length %></td>
                    <td><%= link_to 'Edit', edit_property_path(p)  %></td>
                    <td><%= link_to 'Delete', p, method: :delete  %></td>

                </tr>
            <% end %>    
        </tbody>
    </table>
    <%= link_to 'New Property', new_property_path, {class: 'new-property'} %>
</div>

app/views/properties/new.html.erb
<div class="new">

<%= render 'form', property: @property %>

<%= link_to 'Back', my_properties_properties_path %>

</div>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @property.description %>
</p>

<p>
  <strong>Total area:</strong>
  <%= @property.total_area %>
</p>

<p>
  <strong>Price:</strong>
  <%= @property.price %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>